// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yahaotcqsjlotlqpfuuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhaGFvdGNxc2psb3RscXBmdXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MzUxOTAsImV4cCI6MjA1NzAxMTE5MH0.ycR8JfhX71Q1B16UM03VJ769hyXNQQb5CeA8HKhYPkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});